# Generated by Django 6.0.6 on 2026-06-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='current_requirements',
            field=models.TextField(blank=True, help_text='Free-text summary of active hiring needs.'),
        ),
        migrations.AddField(
            model_name='company',
            name='landline',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='number_of_openings',
            field=models.PositiveIntegerField(default=0, help_text='Declared total open positions across the company.'),
        ),
    ]
