# Generated by Django 6.0.6 on 2026-06-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_company_current_requirements_company_landline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at'], 'verbose_name': 'Institute', 'verbose_name_plural': 'Institutes'},
        ),
        migrations.AddField(
            model_name='company',
            name='institute_type',
            field=models.CharField(choices=[('school', 'School'), ('college', 'College')], db_index=True, default='school', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='school_board',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='university_affiliation',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
