# Generated by Django 6.0.6 on 2026-06-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0004_company_address_company_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='school_board',
        ),
        migrations.AddField(
            model_name='company',
            name='accreditation_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='classes_offered',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='medium_of_instruction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='principal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='school_facilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='school_type',
            field=models.CharField(blank=True, choices=[('cbse', 'CBSE'), ('icse', 'ICSE'), ('state_board', 'State Board'), ('international', 'International'), ('other', 'Other')], max_length=20),
        ),
    ]
