# Generated by Django 6.0.6 on 2026-06-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0005_remove_company_school_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='approval_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='college_accreditation_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='college_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='courses_offered',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='departments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='director_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='naac_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
