# Generated by Django 6.0.6 on 2026-06-14 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0006_company_approval_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message="Only letters, numbers, spaces, and basic punctuation (.,-&') are allowed.", regex="^[A-Za-z0-9\\s\\.\\-\\&,']+$")]),
        ),
        migrations.AlterField(
            model_name='company',
            name='director_name',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message="Only letters, numbers, spaces, and basic punctuation (.,-&') are allowed.", regex="^[A-Za-z0-9\\s\\.\\-\\&,']+$")]),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message="Only letters, numbers, spaces, and basic punctuation (.,-&') are allowed.", regex="^[A-Za-z0-9\\s\\.\\-\\&,']+$")]),
        ),
        migrations.AlterField(
            model_name='company',
            name='principal_name',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message="Only letters, numbers, spaces, and basic punctuation (.,-&') are allowed.", regex="^[A-Za-z0-9\\s\\.\\-\\&,']+$")]),
        ),
    ]
