# Generated by Django 6.0.6 on 2026-06-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0007_alter_company_contact_person_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='company',
            name='number_of_staff',
        ),
        migrations.RemoveField(
            model_name='company',
            name='number_of_students',
        ),
        migrations.RemoveField(
            model_name='company',
            name='size',
        ),
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
    ]
