# Generated by Django 6.0.6 on 2026-06-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0008_remove_company_description_remove_company_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='accreditation_details',
        ),
        migrations.RemoveField(
            model_name='company',
            name='classes_offered',
        ),
        migrations.RemoveField(
            model_name='company',
            name='medium_of_instruction',
        ),
        migrations.RemoveField(
            model_name='company',
            name='principal_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='school_facilities',
        ),
        migrations.RemoveField(
            model_name='company',
            name='school_type',
        ),
    ]
