# Generated by Django 6.0.6 on 2026-06-09 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='qualifications',
            field=models.ManyToManyField(blank=True, related_name='job_seekers', to='jobs.qualification'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='job_seekers', to='jobs.skill'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_seeker',
            field=models.ForeignKey(limit_choices_to={'role': 'job_seeker'}, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['job_seeker', 'recruiter', 'admin'])), name='user_role_valid'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['job_seeker', 'is_primary'], name='accounts_re_job_see_8b9171_idx'),
        ),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('job_seeker',), name='unique_primary_resume_per_seeker'),
        ),
    ]
