# Generated by Django 6.0.6 on 2026-06-09 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_emailverificationtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number in E.164 format, e.g. +919876543210.', regex='^\\+?[1-9]\\d{7,14}$')]),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='current_location',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='designation',
            field=models.CharField(blank=True, help_text='Current or most recent job title.', max_length=150),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_job_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_location',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='subject',
            field=models.CharField(blank=True, help_text="Primary field of study, e.g. 'Computer Science'.", max_length=150),
        ),
    ]
