# Generated by Django 6.0.6 on 2026-06-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jobseekerprofile_alternate_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='district',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='taluka',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
