# Generated by Django 6.0.6 on 2026-06-14 10:42

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auditlog_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='resumes/%Y/%m/', validators=[apps.core.validators.SafeFileValidator(max_size_mb=5)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', validators=[apps.core.validators.SafeFileValidator(allowed_extensions=['.jpg', '.jpeg', '.png', '.webp'], max_size_mb=2)]),
        ),
    ]
