# Generated by Django 6.0.6 on 2026-06-14 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_resume_file_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number consisting only of digits (10 to 15 digits).', regex='^[0-9]{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='E.164 format. Unique — used as an alternate login identifier.', max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number consisting only of digits (10 to 15 digits).', regex='^[0-9]{10,15}$')]),
        ),
    ]
