# Generated by Django 6.0.6 on 2026-06-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_staffprofile_remove_user_user_role_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='city',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='district',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='state',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
