# Generated by Django 6.0.6 on 2026-06-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_staffprofile_city_staffprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('failed_login', 'Failed Login'), ('session_expired', 'Session Expired'), ('device_logout', 'Device Logout')], db_index=True, max_length=20),
        ),
    ]
