# Generated by Django 6.0.6 on 2026-06-09 10:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_approval_status_job_featured_until_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApprovalHistory',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submitted', 'Submitted for Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, max_length=12)),
                ('comment', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_approval_actions', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Job Approval History',
                'verbose_name_plural': 'Job Approval History',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['job', '-created_at'], name='jobs_jobapp_job_id_4f6826_idx')],
            },
        ),
    ]
