# Generated by Django 6.0.6 on 2026-06-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapprovalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='segment',
            field=models.CharField(choices=[('teaching', 'Teaching'), ('healthcare', 'Healthcare'), ('manufacturing', 'Manufacturing'), ('real_estate', 'Real Estate'), ('it', 'Information Technology'), ('other', 'Other')], db_index=True, default='other', max_length=50),
        ),
    ]
