# Generated by Django 6.0.6 on 2026-06-09 18:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_segment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactVisibilityConfig',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_visibility_days', models.PositiveSmallIntegerField(default=2, help_text="How many days a recruiter's contact details stay public after a job is approved & published.")),
                ('is_globally_disabled', models.BooleanField(default=False, help_text='If true, contact details are never shown publicly regardless of per-job state.')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Visibility Config',
                'verbose_name_plural': 'Contact Visibility Config',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobContactVisibility',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('auto', 'Auto (visible until expiry)'), ('show', 'Force show (admin override)'), ('hide', 'Force hide (admin override)'), ('hidden', 'Hidden (expired)')], db_index=True, default='auto', max_length=10)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When AUTO state flips to HIDDEN. Ignored for SHOW/HIDE overrides.')),
                ('last_changed_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_visibility', to='jobs.job')),
                ('overridden_by', models.ForeignKey(blank=True, help_text='Admin who last overrode the automatic state.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Contact Visibility',
                'verbose_name_plural': 'Job Contact Visibility',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['state', 'expires_at'], name='jobs_jobcon_state_db6bec_idx')],
            },
        ),
    ]
