# Generated by Django 6.0.6 on 2026-06-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_contactvisibilityconfig_jobcontactvisibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
