# Generated by Django 6.0.6 on 2026-06-17 17:58

from django.db import migrations, models


def map_experience_levels(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    mapping = {
        'fresher': 'FRESHER',
        'junior': '1_3_YEARS',
        'mid': '3_6_YEARS',
        'senior': '6_10_YEARS',
        'lead': '10_14_YEARS',
    }
    for old_val, new_val in mapping.items():
        Job.objects.filter(experience_level=old_val).update(experience_level=new_val)

def reverse_map_experience_levels(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    mapping = {
        'FRESHER': 'fresher',
        '1_3_YEARS': 'junior',
        '3_6_YEARS': 'mid',
        '6_10_YEARS': 'senior',
        '10_14_YEARS': 'lead',
        '14_18_YEARS': 'lead',
        '18_PLUS_YEARS': 'lead',
    }
    for new_val, old_val in mapping.items():
        Job.objects.filter(experience_level=new_val).update(experience_level=old_val)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_metadata'),
    ]

    operations = [
        migrations.RunPython(map_experience_levels, reverse_map_experience_levels),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('FRESHER', 'Fresher (0 Years)'), ('1_3_YEARS', '1 – 3 Years'), ('3_6_YEARS', '3 – 6 Years'), ('6_10_YEARS', '6 – 10 Years'), ('10_14_YEARS', '10 – 14 Years'), ('14_18_YEARS', '14 – 18 Years'), ('18_PLUS_YEARS', '18+ Years')], db_index=True, max_length=20),
        ),
    ]
