# Generated by Django 6.0.6 on 2026-06-20 10:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_job_requirements_remove_job_skills_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffJob',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('designation', models.CharField(db_index=True, max_length=255)),
                ('job_sub_title', models.CharField(blank=True, max_length=255)),
                ('organization_name', models.CharField(db_index=True, max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('vacancies', models.PositiveIntegerField(default=1)),
                ('offered_salary', models.PositiveIntegerField(db_index=True)),
                ('job_location', models.CharField(db_index=True, max_length=255)),
                ('phone_number', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], db_index=True, default='active', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Job',
                'verbose_name_plural': 'Staff Jobs',
                'ordering': ['-created_at'],
                'permissions': [('can_create_job', 'Can create job'), ('can_edit_job', 'Can edit job'), ('can_close_job', 'Can close job')],
                'abstract': False,
            },
        ),
    ]
