# Generated by Django 6.0.6 on 2026-06-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_staffjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffjob',
            name='job_sub_title',
        ),
    ]
