# Generated by Django 6.0.6 on 2026-06-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_staffjob_description_staffjob_job_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffjob',
            name='job_subtitle',
        ),
    ]
