# Generated by Django 6.0.6 on 2026-06-09 17:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='ads/%Y/%m/')),
                ('target_url', models.URLField(blank=True)),
                ('ad_type', models.CharField(choices=[('popup', 'Popup'), ('scroll_bar', 'Scroll Bar'), ('display_ad', 'Display Ad')], default='display_ad', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sponsored', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-created_at'],
            },
        ),
    ]
