# Generated by Django 6.0.6 on 2026-06-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Timer for popups (in seconds)'),
        ),
    ]
