# Generated by Django 6.0.6 on 2026-06-13 18:27

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_advertisement_clicks_advertisement_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='SevaJobs', max_length=100)),
                ('support_email', models.EmailField(default='support@sevajobs.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Block access for non-admins.')),
                ('allow_registrations', models.BooleanField(default=True)),
                ('auto_approve_jobs', models.BooleanField(default=False)),
                ('default_meta_title', models.CharField(default='SevaJobs - Find Your Dream Job', max_length=255)),
                ('default_meta_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
