# Generated by Django 6.0.6 on 2026-06-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
