# Generated by Django 6.0.6 on 2026-06-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_location',
            field=models.CharField(blank=True, help_text='Address or meeting link.', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_mode',
            field=models.CharField(blank=True, choices=[('onsite', 'On-site'), ('video', 'Video Call'), ('phone', 'Phone')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='applied', max_length=25),
        ),
    ]
