# Generated by Django 6.0.6 on 2026-06-17 06:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_jobalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_type',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('telephonic', 'Telephonic')], help_text='Online / Offline / Telephonic — ATS preferred classification.', max_length=12),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interviewer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='meeting_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='shortlisted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='shortlisted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortlisted_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interviewing', 'Interviewing'), ('selected', 'Selected'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('archived', 'Archived')], db_index=True, default='applied', max_length=25),
        ),
        migrations.CreateModel(
            name='RecruiterNote',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applications.jobapplication')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_application_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruiter Note',
                'verbose_name_plural': 'Recruiter Notes',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['application', '-created_at'], name='application_applica_d05632_idx')],
            },
        ),
    ]
