# Generated by Django 6.0.6 on 2026-06-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_jobapplication_interview_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_response',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('reschedule_requested', 'Reschedule Requested')], default='pending', help_text="Candidate's RSVP to the scheduled interview.", max_length=25),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_response_note',
            field=models.TextField(blank=True, help_text='Optional note from the candidate.'),
        ),
    ]
