# Generated by Django 6.0.6 on 2026-06-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_add_interview_response_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interviewing', 'Interviewing'), ('interview_completed', 'Completed'), ('decision_pending', 'Decision Pending'), ('interview_cancelled', 'Cancelled'), ('selected', 'Selected'), ('offer_sent', 'Offer Sent'), ('offer_accepted', 'Offer Accepted'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('archived', 'Archived')], db_index=True, default='applied', max_length=25),
        ),
    ]
