# Generated by Django 6.0.6 on 2026-06-17 08:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_jobapplication_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSelection',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selection', to='applications.jobapplication')),
                ('selected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate Selection',
                'verbose_name_plural': 'Candidate Selections',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferDetails',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Offer Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('joined', 'Joined')], db_index=True, default='pending', max_length=20)),
                ('monthly_salary', models.PositiveIntegerField()),
                ('annual_ctc', models.PositiveIntegerField()),
                ('probation_period', models.CharField(blank=True, max_length=100)),
                ('benefits', models.TextField(blank=True)),
                ('working_hours', models.CharField(blank=True, max_length=100)),
                ('joining_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_details', to='applications.jobapplication')),
            ],
            options={
                'verbose_name': 'Offer Detail',
                'verbose_name_plural': 'Offer Details',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
