# Generated by Django 5.2.15 on 2026-06-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_candidaterejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetails',
            name='additional_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='institution_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='institution_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='institution_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offerdetails',
            name='salary_package',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='offerdetails',
            name='annual_ctc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offerdetails',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offerdetails',
            name='monthly_salary',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offerdetails',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('joined', 'Joined')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='offerdetails',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
