# Generated by Django 5.2.15 on 2026-06-17 10:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_offerdetails_additional_terms_and_more'),
        ('jobs', '0006_job_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('composer_opened', 'WhatsApp Composer Opened'), ('message_edited', 'WhatsApp Message Edited'), ('redirect_triggered', 'WhatsApp Redirect Triggered'), ('offer_sent', 'Offer Message Sent')], help_text='The type of action tracked.', max_length=50)),
                ('message_text', models.TextField(blank=True, help_text='The customized text message.')),
                ('candidate', models.ForeignKey(help_text='The candidate to whom the message was targeted.', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_received_logs', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(help_text='The job related to the selection/offer.', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_logs', to='jobs.job')),
                ('recruiter', models.ForeignKey(help_text='The recruiter who triggered/sent the message.', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_sent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Log',
                'verbose_name_plural': 'WhatsApp Logs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
