# Generated by Django 6.0.6 on 2026-06-20 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_staffprofile_remove_user_user_role_valid_and_more'),
        ('applications', '0012_alter_jobalert_experience_level'),
        ('jobs', '0009_staffjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobapplication',
            name='unique_application_per_job',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='staff_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.staffjob'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['staff_job', 'status'], name='application_staff_j_5b03f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('job__isnull', False)), fields=('job', 'applicant'), name='unique_application_per_job'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('staff_job__isnull', False)), fields=('staff_job', 'applicant'), name='unique_application_per_staff_job'),
        ),
    ]
