# Generated by Django 6.0.6 on 2026-06-09 10:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='ads/%Y/%m/')),
                ('target_url', models.URLField()),
                ('placement', models.CharField(choices=[('homepage_banner', 'Homepage Banner'), ('sidebar', 'Sidebar'), ('job_list', 'Job List'), ('job_detail', 'Job Detail')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired')], db_index=True, default='pending', max_length=10)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='recruiters.recruiterprofile')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['placement', 'status', 'starts_at', 'ends_at'], name='advertiseme_placeme_00d69e_idx')],
            },
        ),
    ]
