# Generated by Django 6.0.6 on 2026-06-09 15:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0004_job_segment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=20)),
                ('alternate_mobile', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('current_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('applying_position', models.CharField(choices=[('prt', 'Primary Teacher (PRT)'), ('tgt', 'Trained Graduate Teacher (TGT)'), ('pgt', 'Post Graduate Teacher (PGT)'), ('lecturer', 'Lecturer'), ('assistant_professor', 'Assistant Professor'), ('professor', 'Professor'), ('principal', 'Principal'), ('other', 'Other')], max_length=30)),
                ('subject_specialization', models.CharField(max_length=100)),
                ('total_experience_years', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('current_employer', models.CharField(blank=True, max_length=150)),
                ('current_designation', models.CharField(blank=True, max_length=100)),
                ('current_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('notice_period_days', models.PositiveSmallIntegerField(default=0)),
                ('immediate_joining', models.BooleanField(default=False)),
                ('career_objective', models.TextField(blank=True)),
                ('why_join_us', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('awards_recognition', models.TextField(blank=True)),
                ('research_publications', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherLanguage',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=50)),
                ('can_read', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=True)),
                ('can_speak', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='teaching.teacherprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherDocument',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('resume', 'Resume (PDF)'), ('photo', 'Passport Photo'), ('education_cert', 'Educational Certificates'), ('experience_cert', 'Experience Certificates'), ('teaching_cert', 'Teaching Certifications'), ('additional', 'Additional Documents')], max_length=30)),
                ('file', models.FileField(upload_to='teacher_docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='teaching.teacherprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherCertification',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certification_name', models.CharField(choices=[('b_ed', 'B.Ed'), ('d_ed', 'D.Ed'), ('m_ed', 'M.Ed'), ('ctet', 'CTET'), ('tet', 'TET'), ('net', 'NET'), ('set', 'SET'), ('montessori', 'Montessori Certification'), ('other', 'Other Professional Certifications')], max_length=30)),
                ('year_obtained', models.PositiveIntegerField(blank=True, null=True)),
                ('authority', models.CharField(blank=True, max_length=150)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='teaching.teacherprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qualification', models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('diploma', 'Diploma'), ('graduation', 'Graduation'), ('post_graduation', 'Post Graduation'), ('phd', 'PhD'), ('other', 'Other Certifications')], max_length=20)),
                ('institution_name', models.CharField(max_length=200)),
                ('board_university', models.CharField(max_length=200)),
                ('year_of_passing', models.PositiveIntegerField()),
                ('percentage_cgpa', models.CharField(max_length=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_details', to='teaching.teacherprofile')),
            ],
            options={
                'ordering': ['-year_of_passing'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherSkill',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(choices=[('classroom_management', 'Classroom Management'), ('lesson_planning', 'Lesson Planning'), ('curriculum_development', 'Curriculum Development'), ('online_teaching', 'Online Teaching'), ('smart_board', 'Smart Board Usage'), ('google_classroom', 'Google Classroom'), ('zoom', 'Zoom'), ('ms_teams', 'Microsoft Teams'), ('student_assessment', 'Student Assessment'), ('parent_communication', 'Parent Communication'), ('other', 'Other Skills')], max_length=40)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='teaching.teacherprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeachingExperience',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('subject_taught', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('guest', 'Guest Faculty')], default='full_time', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('roles_and_responsibilities', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='teaching.teacherprofile')),
            ],
            options={
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeachingApplication',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('years_experience_subject', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('can_teach_online', models.BooleanField(default=False)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('english_medium_instruction', models.BooleanField(default=False)),
                ('expected_joining_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='submitted', max_length=30)),
                ('employer_notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_applications', to='jobs.job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='teaching.teacherprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('profile', 'job')},
            },
        ),
    ]
