# Generated by Django 6.0.6 on 2026-06-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_received', 'Application Received'), ('status_changed', 'Application Status Changed'), ('application_shortlisted', 'Application Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('application_selected', 'Application Selected'), ('application_rejected', 'Application Rejected'), ('job_posted', 'Job Posted'), ('job_approved', 'Job Approved'), ('job_rejected', 'Job Rejected'), ('job_expiring', 'Job Expiring Soon'), ('profile_viewed', 'Profile Viewed'), ('system', 'System')], db_index=True, max_length=30),
        ),
    ]
