# Generated by Django 6.0.6 on 2026-06-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_notification_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_received', 'Application Received'), ('status_changed', 'Application Status Changed'), ('application_shortlisted', 'Application Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('application_selected', 'Application Selected'), ('application_rejected', 'Application Rejected'), ('job_posted', 'Job Posted'), ('job_approved', 'Job Approved'), ('job_rejected', 'Job Rejected'), ('job_expiring', 'Job Expiring Soon'), ('profile_viewed', 'Profile Viewed'), ('system', 'System'), ('job_assigned', 'Job Assigned'), ('job_reassigned', 'Job Reassigned'), ('recruitment_completed', 'Recruitment Completed'), ('candidate_selected', 'Candidate Selected'), ('high_app_volume', 'High Application Volume')], db_index=True, max_length=30),
        ),
    ]
