# Generated by Django 5.2.17 on 2026-09-20 09:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('bounce', 'Permanent Bounce'), ('complaint', 'Spam Complaint'), ('manual', 'Manual Suppression')], db_index=True, default='bounce', max_length=20)),
                ('bounce_type', models.CharField(blank=True, max_length=50)),
                ('bounce_sub_type', models.CharField(blank=True, max_length=50)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Raw event payload from AWS SNS.')),
            ],
            options={
                'verbose_name': 'Email Suppression',
                'verbose_name_plural': 'Email Suppressions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
